apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"

jobs:
  build:
    steps:

      # Step 1: Checkout Code
      - name: Checkout Code
        kind: build
        uses: docker://alpine/git:latest
        run: |
          git clone https://github.com/avinash1617/sample-java-app.git
          ls -l

      # Step 2: Maven Build
      - name: Maven Build
        kind: build
        uses: docker://maven:3.9.14-eclipse-temurin-8
        run: |
          cd sample-java-app
          mvn clean package

      # Step 3: Generate SBOM
      - name: Generate SBOM
        kind: scan
        uses: docker://anchore/syft:latest
        entrypoint: syft
        args:
          - dir:/cloudbees/workspace/sample-java-app
          - -o
          - cyclonedx-json

      # Step 4: Filesystem Vulnerability Scan
      - name: Trivy Scan
        kind: scan
        uses: docker://aquasec/trivy:latest
        entrypoint: trivy
        args:
          - fs
          - /cloudbees/workspace/sample-java-app
